# -*- coding: utf-8 -*-
"""Model project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1yp3i3iIKG5ZcOlMW7vmPdmNxEPINPS

##SUPERVISED ML

###Healthcare-Stroke Prediction

####By using health information to predict if a person might have a stroke and helpingin early care and prevention

##Classification Algorithms

##Decision Tree Classifier
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

iris=load_iris()

df=pd.DataFrame(data=iris.data,columns=iris.feature_names)

df

from google.colab import files
up=files.upload()

data=pd.read_csv(r'healthcare-dataset-stroke-data.csv')

df=pd.DataFrame(data)

df

df.dropna(inplace=True)

df.duplicated().sum()

df.isnull().sum()

df

df['gender']=df['gender'].replace("Male",1)
df['gender']=df['gender'].replace("Female",0)
df['gender']=df['gender'].replace("Other",2)
df['ever_married']=df['ever_married'].replace("Yes",1)
df['ever_married']=df['ever_married'].replace("No",0)
df['Residence_type']=df['Residence_type'].replace("Urban",1)
df['Residence_type']=df['Residence_type'].replace("Rural",0)
df['work_type']=df['work_type'].replace("Govt_job",0)
df['work_type']=df['work_type'].replace("Private",1)
df['work_type']=df['work_type'].replace("Self-employed",2)
df['work_type']=df['work_type'].replace("children",3)
df['work_type']=df['work_type'].replace("Never_worked",4)
df['smoking_status']=df['smoking_status'].replace("Unknown",0)
df['smoking_status']=df['smoking_status'].replace("formerly smoked",1)
df['smoking_status']=df['smoking_status'].replace("never smoked",2)
df['smoking_status']=df['smoking_status'].replace("smokes",3)

x=df[['age','bmi','gender','ever_married','work_type','smoking_status','Residence_type','avg_glucose_level']]

y=df['stroke']

x

y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

model=DecisionTreeClassifier(random_state=42)

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

print("acc",accuracy_score(y_test,y_pred))

import seaborn as sns
cm=confusion_matrix(y_test,y_pred)

sns.heatmap(cm,annot=True)

cm



"""##Graphs"""

data.info()

df.describe()

avg=df['stroke'].mean()

group=df.groupby('work_type')['stroke'].mean()

avg

df['stroke'].fillna(avg,inplace=True)

df

df['work_type'].fillna("not mentioned",inplace=True)

df

df['gender']=df['gender'].replace("Male","M")

df

df['gender']=df['gender'].replace("Female","F")

df

df['stroke+10']=df['stroke']+10

df

stroke_mean=df['stroke'].mean()
median=df['stroke'].median

df

group=df.groupby('work_type')['stroke'].mean()

group

pivot=pd.pivot_table(df,
                     values="stroke",
                     index="work_type",
                     columns="gender",
                     aggfunc=['mean','sum']
                     )

pivot

import matplotlib.pyplot as plt

plt.bar(df['work_type'],df['stroke'],color='violet')
plt.xlabel("work_type")
plt.ylabel('stroke')
plt.xticks(rotation=45)
plt.title("work_type VS stroke")
plt.show()

plt.hist(df['work_type'],color='green',bins=4)
plt.xlabel("work_type")
plt.ylabel('stroke')
plt.xticks(rotation=45)
plt.title("work_type VS stroke")
plt.show()

plt.pie(group , labels=['Never_worked','children','Private', 'Govt_job','Self-employed'])
plt.legend()
plt.show()

plt.plot(group)
plt.show()

plt.figure(figsize=(16,12))
plt.suptitle("healthcare-dataset-stroke Dashboard", fontsize=18)
plt.subplot(3,2,1)
plt.plot(group)
plt.title("Group Line Plot")
plt.xlabel("Index")
plt.ylabel("Values")
plt.subplot(3,2,2)
plt.pie(group, labels=['Never_worked','children','Private', 'Govt_job','Self-employed'])
plt.title("Group Pie Chart")
plt.legend(loc='best')
plt.subplot(3,2,3)
plt.hist(df['work_type'], color='green', bins=4)
plt.xlabel("work_type")
plt.ylabel("stroke")
plt.xticks(rotation=45)
plt.title("work_type Vs stroke Histogram")
plt.subplot(3,2,4)
plt.bar(df['work_type'], df['stroke'], color='violet')
plt.xlabel("work_type")
plt.ylabel("stroke")
plt.xticks(rotation=45)
plt.title("work_type VS stroke (Bar)")
plt.tight_layout()
plt.show()

"""##To Download Model"""

import pickle

with open("model.pkl", "wb")as f:
  pickle.dump(model, f)

from google.colab import files
files.download("model.pkl")

import pickle
pickle.dump(model,open("model.pkl","wb"))

